services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DATABASE : corcoiote
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : admin
    ports:
      
      - 5432:5432
    volumes: 
    - postgres:/var/lib/portgres/corcoiote
volumes:
  postgres:
